# Generated by Django 4.1.4 on 2023-02-19 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(default='', max_length=100, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('title', models.CharField(blank=True, max_length=50)),
                ('number', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=100)),
                ('ava', models.ImageField(blank=True, upload_to='avatars')),
                ('facebook', models.CharField(blank=True, max_length=1000)),
                ('instagram', models.CharField(blank=True, max_length=1000)),
                ('youtube', models.CharField(blank=True, max_length=1000)),
                ('telegram', models.CharField(blank=True, max_length=1000)),
                ('twitter', models.CharField(blank=True, max_length=1000)),
                ('tiktok', models.CharField(blank=True, max_length=1000)),
                ('pinterest', models.CharField(blank=True, max_length=1000)),
                ('snapChat', models.CharField(blank=True, max_length=1000)),
                ('linkedin', models.CharField(blank=True, max_length=1000)),
                ('tumbler', models.CharField(blank=True, max_length=1000)),
                ('vk', models.CharField(blank=True, max_length=1000)),
                ('discord', models.CharField(blank=True, max_length=1000)),
                ('twitch', models.CharField(blank=True, max_length=1000)),
                ('quora', models.CharField(blank=True, max_length=1000)),
                ('whatsapp', models.CharField(blank=True, max_length=1000)),
                ('github', models.CharField(blank=True, max_length=1000)),
                ('sinaweibo', models.CharField(blank=True, max_length=1000)),
                ('viber', models.CharField(blank=True, max_length=1000)),
                ('skype', models.CharField(blank=True, max_length=1000)),
                ('soundCloud', models.CharField(blank=True, max_length=1000)),
                ('spotify', models.CharField(blank=True, max_length=1000)),
                ('their_website1', models.CharField(blank=True, max_length=1000)),
                ('their_website2', models.CharField(blank=True, max_length=1000)),
                ('their_website3', models.CharField(blank=True, max_length=1000)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
