# Generated by Django 4.1.4 on 2023-02-19 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Company',
        ),
    ]
