# Generated by Django 4.1.4 on 2023-02-19 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_rename_user_company'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='name',
            new_name='username',
        ),
    ]
