# Generated by Django 4.1.4 on 2023-02-28 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='username',
            new_name='company_name',
        ),
    ]
