# Generated by Django 4.1.4 on 2023-02-28 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_rename_username_company_company_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Company',
            new_name='CompanyModel',
        ),
    ]
