# Generated by Django 4.1.4 on 2023-02-28 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_rename_company_companymodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CompanyModel',
            new_name='Company',
        ),
    ]
