# Generated by Django 4.1.4 on 2023-02-28 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_rename_companymodel_company'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='company_name',
            new_name='username',
        ),
    ]
