# Generated by Django 4.1.4 on 2023-02-28 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_rename_company_name_company_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='username',
            new_name='name',
        ),
    ]
